---
apiVersion: v1
kind: Secret
metadata:
  name: bowsecret-tls
  namespace: default
data:
  tls.crt: 
  tls.key: 
type: kubernetes.io/tls
---
apiVersion: v1
data:
  FILE_PATH: /data/files
  AWS_ENDPOINT_URL: "https://s3.ap-south-1.amazonaws.com"
  AWS_ACCESS_KEY: ""
  AWS_SECRET_KEY: ""
  AWS_BUCKET_NAME: "bow-sg"
  MONGO_URL: "mongodb://admin:password@mongo:27017/boozeonwheel?authSource=admin"
kind: ConfigMap
metadata:
  name: bow-api-config
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bow-api-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bow-api-app
  template:
    metadata:
      labels:
        app: bow-api-app
    spec:
      volumes:
      - name: mypd
        persistentVolumeClaim:
          claimName: mongo-persistent-storage
      containers:
        -
          env:

            -
              name: FILE_PATH
              valueFrom:
                configMapKeyRef:
                  key: FILE_PATH
                  name: bow-api-config
            -
              name: AWS_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  key: AWS_ENDPOINT_URL
                  name: bow-api-config

            -
              name: AWS_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: AWS_ACCESS_KEY
                  name: bow-api-config
            -
              name: AWS_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: AWS_SECRET_KEY
                  name: bow-api-config

            -
              name: AWS_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  key: AWS_BUCKET_NAME
                  name: bow-api-config
            -
              name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  key: MONGO_URL
                  name: bow-api-config

          image: "lalit1980/bow-product-svc:tagVersion"
          volumeMounts:
          - mountPath: "/data/files"
            name: mypd
          imagePullPolicy: Always
          name: bow-api-app
          ports:
            -
              containerPort: 9010
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: bow-api-service
  namespace: default
spec:
  clusterIP: None
  ports:
    - port: 9010 # custom value.
  selector:
    app: bow-api-app
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: lalit.yadav@boozeonwheels.co
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bow-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - boozeonwheels.com
    secretName: bowsecret-tls
  rules:
  - host: boozeonwheels.com
    http:
      paths:
      - backend:
          serviceName: bow-api-service
          servicePort: 9010
