# Spring boot settings
spring:
  profiles: dev
  application:
    name: bow-auth-svc
  servlet:
    multipart:
      maxRequestSize: 70000000
      maxFileSize: 70000000
  main:
    allow-bean-definition-overriding: true

  jmx:
    enabled: false

  data:
    mongodb:
      host: localhost
      port: 27017
      database: authsvc

# --------------------------------------------------------------------------------------------------
mongo:
  min-connections: 2
  max-connections: 5
  connect-timeout-ms: 5000
  socket-timeout-ms: 5000

# --------------------------------------------------------------------------------------------------

# The embedded server settings
server:
  address: localhost
  port: 8082

# --------------------------------------------------------------------------------------------------

# Customise active actuator endpoints
endpoints:
  configprops:
    enabled: false
  info:
    enabled: false
  shutdown:
    enabled: false



bow:
  app:
    jwtSecret: 
    jwtExpirationMs: 86400000

aws:
  access-key: 
  access-secret: 
  default-region: ap-southeast-1

