# Spring boot settings
spring:
  profiles: dev
  application:
    name: bow-auth-svc
  servlet:
    multipart:
      maxRequestSize: 70000000
      maxFileSize: 70000000
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_FSX6yqAUv

  jmx:
    enabled: false

  data:
    mongodb:
      host: localhost
      port: 27017
      database: authsvc

# --------------------------------------------------------------------------------------------------
mongo:
  min-connections: 2
  max-connections: 5
  connect-timeout-ms: 5000
  socket-timeout-ms: 5000

# --------------------------------------------------------------------------------------------------

# The embedded server settings
server:
  address: localhost
  port: 8082

# --------------------------------------------------------------------------------------------------

# Customise active actuator endpoints
endpoints:
  configprops:
    enabled: false
  info:
    enabled: false
  shutdown:
    enabled: false



bow:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000

aws:
  access-key: AKIAYHND4XDR6YS4TEEA
  access-secret: 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
  default-region: ap-southeast-1
  cognito:
    clientId: 5s0mcs7ukg98n5h0tpftqn68mv
    userPoolId: ap-southeast-1_FSX6yqAUv
    region: ap-southeast-1
    connectionTimeout: 2000
    readTimeout: 2000
    jwk: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_FSX6yqAUv/.well-known/jwks.json
